// Portfolio project data — sourced from Showmiq Islam Utshow's
// MSJ4299 Portfolio Report, ULAB Department of Media Studies & Journalism.
const PROJECTS = [
  {
    id: 1,
    image: "images/projects/project-01.jpg",
    pdf: "pdfs/project-01.pdf",
    group: "common",
    course: "MSJ1201 · Communication Research",
    title: "Research on Millennials",
    type: "Research Proposal",
    term: "Summer 2022",
    summary: "A research proposal on how millennials identify — or fail to identify — misinformation on social media.",
    description: "This research studies how well millennials understand and identify false information on social media. It looks at how they check, believe, and share information online. The study uses in-depth interviews with selected millennials, and the findings identify common behaviors and the effects of misinformation on people and society.",
    justification: "Misinformation and false news are increasing rapidly on social media, and millennials play an important role in consuming and sharing information online — as parents and community members, they also influence younger generations. This research identifies gaps in their ability to check and recognize false information, work that can help promote responsible media use and reduce the spread of misinformation.",
    tags: ["Research", "Misinformation", "Media Literacy"]
  },
  {
    id: 2,
    image: "images/projects/project-02.jpg",
    pdf: "pdfs/project-02.pdf",
    group: "common",
    course: "MSJ2101 · Communication and Technology",
    title: "Patriarchy",
    type: "Blog Writing",
    term: "Fall 2022",
    summary: "A blog piece unpacking how patriarchy shapes men's emotions and their ideas of masculinity.",
    description: "This project explores how patriarchy affects men's emotions, behavior, and ideas of masculinity. It focuses on how boys are taught from a young age to hide their emotions and always appear strong, and it examines the pressure men face to be providers, protectors, and emotionally stable.",
    justification: "These expectations can make men feel that showing emotion is a sign of weakness. The piece aims to encourage men to express their feelings, ask for help, and accept vulnerability without shame, promoting a healthier and more open understanding of masculinity.",
    tags: ["Gender", "Op-Ed", "Society"]
  },
  {
    id: 3,
    image: "images/projects/project-03.jpg",
    pdf: "pdfs/project-03.pdf",
    group: "common",
    course: "MSJ2201 · Mass Communication",
    title: "Behind the Screen",
    type: "Mask Making",
    term: "Summer 2023",
    summary: "A conceptual mask, exhibited at Bangladesh Shilpakala Academy, on social media and youth mental health.",
    description: "This project explored the relationship between social media and the mental and social well-being of young people, focusing on group polarization and how social media can influence thoughts and emotions. A conceptual mask was built to show two contrasting sides of youth — one happy and socially active, the other isolated and in emotional distress — using symbols like a smartphone and a handmade knife. The mask was exhibited at Bangladesh Shilpakala Academy, where viewers were interviewed about the effectiveness of the concept.",
    justification: "The project highlights the growing impact of social media on young people's emotional and social well-being. While social media helps people connect, excessive use, trolling, and social comparison can cause loneliness, anxiety, and distress — the mask visualized the gap between how people appear and what they may feel inside.",
    tags: ["Mental Health", "Installation", "Exhibited"]
  },
  {
    id: 4,
    image: "images/projects/project-04.jpg",
    pdf: "pdfs/project-04.pdf",
    group: "common",
    course: "GEF1202 · Advanced English Writing Skills",
    title: "Islamophobia & Drug Trafficking",
    type: "English Feature Writing",
    term: "Fall 2022",
    summary: "Two persuasive pieces — an opinion article on Islamophobia in the West, an editorial on drug trafficking in Bangladesh.",
    description: "This project consists of two pieces of persuasive writing: an opinion article examining Islamophobia in Western societies, and an editorial addressing the problem of drug trafficking in Bangladesh. Both pieces apply feature and opinion-writing conventions to real, socially relevant issues rather than a single narrative subject.",
    justification: "Islamophobia and drug trafficking are current, socially significant issues that made it possible to practice persuasive structure, evidence-based argument, and an engaging journalistic voice — the exact skills the course targets.",
    tags: ["Opinion Writing", "Feature Writing", "Social Issues"]
  },
  {
    id: 5,
    image: "images/projects/project-05.jpg",
    pdf: "pdfs/project-05.pdf",
    group: "common",
    course: "MSJ2231 · Visual Communication",
    title: "Unequal Grief",
    type: "Installation Art",
    term: "Fall 2025",
    summary: "An installation on necropolitics — why some deaths command global attention and others become statistics.",
    description: "This project explores how society assigns different values to human deaths during political violence. Inspired by Benazir Bhutto's assassination, it examines why prominent figures receive greater media attention than ordinary victims. The installation uses one large coffin to represent a political leader and smaller coffins for civilians and soldiers, with a freely moving camera repeatedly focused on the large coffin to symbolize the media's selective attention.",
    justification: "The project questions how media, political power, and public attention determine whose deaths are considered significant — highlighting how political leaders receive collective mourning while ordinary victims are reduced to statistics, and encouraging viewers to ask why some deaths remain in public memory while others are forgotten.",
    tags: ["Necropolitics", "Installation", "Media Framing"]
  },
  {
    id: 6,
    image: "images/projects/project-06.jpg",
    pdf: "pdfs/project-06.pdf",
    group: "common",
    course: "MSJ2102 · Convergence Communication I",
    title: "Restoring Harmony",
    type: "Trashion Show",
    term: "Fall 2023",
    summary: "A trashion show contrasting a healthy forest with a polluted one, built entirely from recycled waste.",
    description: "Restoring Harmony is a fashion-based environmental awareness project built around ecosystem and forest restoration. A Trashion Show visually contrasted a healthy forest with one damaged by pollution and deforestation, using two models — one representing Mother Nature in green and blue, the other a damaged, polluted forest — dressed in recycled polythene, plastic bags, glue, and other discarded materials.",
    justification: "The project highlights the urgent need to restore ecosystems damaged by human activity. Turning discarded materials into fashion transforms waste into creative communication, using the contrast between Mother Nature and the polluted forest to visually show the impact of human action — and to encourage people to protect and restore nature.",
    tags: ["Sustainability", "Fashion", "Live Show"]
  },
  {
    id: 7,
    image: "images/projects/project-07.jpg",
    pdf: "pdfs/project-07.pdf",
    group: "common",
    course: "MSJ2202 · Convergence Communication II",
    title: "Discombobulated Predicament",
    type: "Video Art",
    term: "Spring 2024",
    summary: "A four-shot video using masks and dance to explore how judgment suppresses self-expression.",
    description: "\u201cDiscombobulated Predicament\u201d explores how free expression supports learning and personal growth, and how social expectations and judgment can suppress it. The four-shot video uses masks, public judgment, dance, and shared human experience to communicate the struggle, and the accompanying concept paper outlines the cast, locations, equipment, props, and music required for production.",
    justification: "The concept examines how social pressure and fear of judgment restrict people from expressing themselves. Mask imagery, movement, and mixed-media stop-motion let the idea come across visually and abstractly rather than through direct narration — practice in conceptual video-art development, shot planning, and production coordination.",
    tags: ["Video Art", "Self-Expression", "Production"]
  },
  {
    id: 8,
    image: "images/projects/project-08.jpg",
    pdf: "pdfs/project-08.pdf",
    group: "major",
    course: "MSJ11241 · Interpersonal & Intercultural Communication",
    title: "Cultural Barriers, Up Close",
    type: "Reflective Paper",
    term: "Spring 2025",
    summary: "A reflective paper applying Hofstede's cultural dimensions to real cross-cultural scenarios.",
    description: "The paper defines culture and how it is expressed — language, non-verbal communication, art, tradition, social norms — and explains why intercultural communication matters in academic, professional, and diplomatic settings. It then analyzes two scenarios: adapting as a Bangladeshi student to the UK's educational and social environment, and understanding Bangladesh–Japan communication differences through Hofstede's six cultural dimensions.",
    justification: "The topic reflects on my own potential experience navigating unfamiliar cultural environments and applies theoretical frameworks like cultural relativism and Hofstede's dimensions to real cross-cultural scenarios — directly relevant to a field where working with diverse audiences and international collaborators requires cultural awareness and adaptability.",
    tags: ["Intercultural Comms", "Hofstede", "Reflective"]
  },
  {
    id: 9,
    image: "images/projects/project-09.jpg",
    pdf: "pdfs/project-09.pdf",
    group: "major",
    course: "MSJ11342 · Public Relation Research",
    title: "Social Media in Modern PR",
    type: "Research Paper",
    term: "Summer 2024",
    summary: "Surveys and interviews with PR practitioners on how social media is reshaping PR strategy in Bangladesh.",
    description: "This study uses surveys and in-depth interviews with PR practitioners and social media managers to examine social media's impact on PR strategy. It explores communication, audience engagement, and crisis management across Facebook, Instagram, and Twitter, and addresses challenges such as the urban–rural digital divide, misinformation, and the limits of social media in PR.",
    justification: "Social media has become central to how organizations in Bangladesh communicate with the public, yet its specific impact on PR strategy in the local context wasn't fully understood by our group. Researching it meant applying real PR research methodologies — survey design, thematic analysis, sampling — to a fast-evolving communication issue.",
    tags: ["Public Relations", "Social Media", "Bangladesh"]
  },
  {
    id: 10,
    image: "images/projects/project-10.jpg",
    pdf: "pdfs/project-10.pdf",
    group: "major",
    course: "MSJ3142 · Media Relations",
    title: "ULAB Launches Humanitarian Aid",
    type: "Press Release",
    term: "Summer 2024",
    summary: "A press release covering ULAB's humanitarian aid initiative during a period of political crisis.",
    description: "This project involved writing a press release for ULAB's humanitarian aid and support initiative during a period of political crisis in Bangladesh. It communicated the university's relief activities, support for affected communities, and commitment to social responsibility — written to give media clear, usable information while highlighting the university's role during the crisis.",
    justification: "The project demonstrates how effective media relations can communicate an organization's social responsibility and humanitarian efforts. A press release lets important information reach journalists and the public clearly, professionally, and credibly, and shows how universities can use strategic communication to build public awareness during challenging situations.",
    tags: ["Press Release", "Crisis Comms", "Higher Ed"]
  },
  {
    id: 11,
    image: "images/projects/project-11.jpg",
    pdf: "pdfs/project-11.pdf",
    group: "major",
    course: "MSJ3242 · Created Private Media",
    title: "Breaking the Cycle — JAAGO Foundation",
    type: "Corporate Audio Visual",
    term: "Fall 2024",
    summary: "A full production binder for a 4:30 corporate AV following a child's school day at JAAGO Foundation.",
    description: "As the final project for Created Private Media, our group (Prism PR Solutions) produced a full production binder for a corporate AV titled \u201cBreaking the Cycle: A Journey Out of Poverty,\u201d made for the JAAGO Foundation. The binder includes the script, script breakdown, two-day shooting schedule, shot list, reference shots, location list, prop list, crew list, and cast list for a 4-minute-30-second film following a child's school day at a JAAGO Foundation school.",
    justification: "This project gave our group real production-house experience, from scripting and scheduling to on-location shooting for a non-profit client. As Director of Photography for the shoot, and writer of the Brief Information and Crew List sections, I applied cinematography and shot-composition skills to represent JAAGO Foundation's mission authentically and persuasively.",
    tags: ["Non-Profit", "Cinematography", "Production Binder"],
    role: "Director of Photography"
  },
  {
    id: 12,
    image: "images/projects/project-12.jpg",
    pdf: "pdfs/project-12.pdf",
    group: "major",
    course: "MSJ3243 · Speech Writing and Public Speaking",
    title: "Network Propaganda",
    type: "Persuasive Speech",
    term: "Spring 2025",
    summary: "A persuasive speech on echo chambers, AI-generated content, and the machinery of modern misinformation.",
    description: "This project involved writing and delivering a persuasive speech on \u201cNetwork Propaganda\u201d and the spread of misinformation through social media, exploring echo chambers, emotional manipulation, AI-generated content, declining trust, social division, and manipulated elections. Audience demographic, cognitive, affective, behavioral, and SWOT analyses shaped the approach, and the speech closed with a call to action encouraging audiences to think critically and verify what they consume.",
    justification: "Growing concern, as a media studies and journalism student, about how algorithms, emotional framing, and audience segmentation are used to spread false information and manipulate public opinion. The project applied speechwriting technique, audience-analysis frameworks, and persuasive delivery to a topic directly relevant to media literacy.",
    tags: ["Public Speaking", "Misinformation", "Persuasion"],
    featured: true
  },
  {
    id: 13,
    image: "images/projects/project-13.jpg",
    pdf: "pdfs/project-13.pdf",
    group: "major",
    course: "MSJ4141 · Advertising",
    title: "United Beyond Beliefs",
    type: "Production Proposal (Advertisement)",
    term: "Fall 2024",
    summary: "A PSA proposal following a Hindu and a Muslim friend supporting each other through everyday moments.",
    description: "For this advertising production proposal, my group developed a public service advertisement titled \u201cUnited Beyond Beliefs,\u201d telling the story of a Hindu and a Muslim friend supporting each other through everyday moments and religious practices. The proposal includes the full scene-by-scene script, supporting research on religious harmony and Gen Z's political and social attitudes in Bangladesh, target audience analysis, the intended persuasive message, and each group member's contribution.",
    justification: "The advertisement was built to persuade Gen Z viewers — who research shows increasingly reject mixing religion with politics — to see past religious divisions and value shared humanity, especially given youth-led movements' recent influence on political change in Bangladesh. As Director and Cinematographer for the video, and researcher for the proposal, I translated this message into visual storytelling.",
    tags: ["PSA", "Religious Harmony", "Gen Z"],
    role: "Director & Cinematographer"
  },
  {
    id: 14,
    image: "images/projects/project-14.jpg",
    pdf: "pdfs/project-14.pdf",
    group: "major",
    course: "MSJ4142 · Public Relations Campaign",
    title: "Rolls-Royce Black Badge — Case Analysis",
    type: "Case Analysis",
    term: "Spring 2025",
    summary: "A case analysis of Rolls-Royce's Black Badge campaign, and how it courted a younger luxury buyer.",
    description: "This project analyzes Rolls-Royce's Black Badge PR campaign, which repositioned the brand to appeal to younger, modern luxury consumers. It examines the campaign's objectives, target audience, SWOT analysis, messaging, communication channels, creative tactics, and outcomes — including a shift in average buyer age from 56 to 43 and Black Badge models growing to over 27% of worldwide sales.",
    justification: "The project explores how Rolls-Royce modernized its heritage image while preserving its core identity and attracting younger consumers. The Black Badge campaign shows how PR, storytelling, digital media, experiential marketing, and influencers can work together to make a luxury brand more relevant to a new generation.",
    tags: ["PR Campaign", "Luxury Branding", "Case Study"],
    featured: true
  }
];
